services:
  image-cleaner:
    build: .
    # environment:
    #   AWS_ACCESS_KEY_ID: your_aws_access_key
    #   AWS_SECRET_ACCESS_KEY: your_aws_secret_key
    #   AWS_REGION: your_aws_region
    volumes:
      - ~/.aws:/root/.aws
      - ./logs:/app/logs
networks:
  default:
    name: nivoda-network
    external: true
